name: Validate Documentation Static Content Generation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Hugo Documentation Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Hugo Static Content image
      run: docker build .
